export const SHIFT_DEFS = {
  M: {
    code: "M",
    label: "Morning",
    short: "M",
    startMin: 7 * 60,
    endMin: 15 * 60,
    overnight: false,
    kind: "day",
    hours: 8,
  },
  "M+A": {
    code: "M+A",
    label: "Day 12h",
    short: "M+A",
    startMin: 7 * 60,
    endMin: 19 * 60,
    overnight: false,
    kind: "day",
    hours: 12,
  },
  "E+N": {
    code: "E+N",
    label: "Eve + Night",
    short: "E+N",
    startMin: 19 * 60,
    endMin: 7 * 60,
    overnight: true,
    kind: "night",
    hours: 12,
  },
  N: {
    code: "N",
    label: "Night",
    short: "N",
    startMin: 23 * 60,
    endMin: 7 * 60,
    overnight: true,
    kind: "night",
    hours: 8,
  },
};

export const DEFAULT_SETTINGS = {
  commuteMin: 30,
  jkStartMin: 19 * 60,
  jkDurationMin: 120,
  mcatWorkMin: 120,
  mcatWorkMinMax: 180,
  mcatOffMin: 360,
  sleepWorkMin: 7 * 60,
  sleepOffMin: 8 * 60,
  sleepMaxMin: 12 * 60,
  wakeDayMin: 6 * 60,
  wakeOffMin: 8 * 60,
  breakfastWorkMin: 30,
  dinnerWorkMin: 60,
  breakfastOffMin: 60,
  lunchOffMin: 60,
  dinnerOffMin: 60,
  mealGapMin: 4 * 60,
  laundryMin: 60,
  laundryEveryDays: 7,
  groceriesMin: 90,
  groceriesEveryDays: 14,
  mealPrepMin: 90,
  mealPrepPerWeek: 2,
  gymMin: 90,
  gymPerWeek: 3,
  choresWeekMin: 150,
  choresWeekMax: 240,
  alarmLeadMin: 10,
  notepadRemindMin: 21 * 60 + 30,
  callParentsOnCommute: true,
  timeZone: null,
  alarmsEnabled: true,
  wakeAlarms: true,
  shiftAlarms: true,
  leaveAlarms: true,
  snoozeMin: 9,
};

export const CATEGORIES = {
  sleep: { label: "Sleep", tone: "sleep" },
  recovery: { label: "Recovery sleep", tone: "recovery" },
  work: { label: "Shift", tone: "work" },
  commute: { label: "Commute", tone: "commute" },
  meal: { label: "Meal", tone: "meal" },
  prayer: { label: "JK", tone: "prayer" },
  study: { label: "MCAT", tone: "study" },
  gym: { label: "Gym", tone: "gym" },
  chore: { label: "Chore", tone: "chore" },
  personal: { label: "Personal", tone: "personal" },
};
