export const DEFAULT_SETTINGS = {
  sleepMaxMin: 12 * 60,
  alarmLeadMin: 10,
  schoolWalkMin: 10,
  schoolTrafficMin: 0,
  beforeSleepNotes: true,
  notepadRemindMin: 21 * 60 + 30,
  callParentsOnCommute: true,
  callParentsDelayMin: 5,
  timeZone: null,
  alarmsEnabled: true,
  wakeAlarms: true,
  shiftAlarms: true,
  classAlarms: true,
  leaveAlarms: true,
  snoozeMin: 9,
  wakeVerificationEnabled: true,
  wakeVerificationMethod: "math",
  mathDifficulty: "medium",
  mathQuestionCount: 1,
  backupAlarmCount: 4,
  backupIntervalSec: 30,
  backupIntervalMin: 1,
};
